apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: xqbit
build:
  artifacts:
    - image: ghcr.io/x-shikanime/xqbit/qbittorrent-cleanup
      context: cmd/qbittorrent-cleanup
      ko: {}
      platforms:
        - linux/amd64
        - linux/arm64
